@startuml actoresYCasosDeUso-administradorInstitucional

left to right direction

actor "Administrador Institucional" as admin

package "Módulo Docentes" {
  usecase "crearDocente()" as UC32
  usecase "verDocentes()" as UC33
  usecase "editarDocente()" as UC34
  usecase "eliminarDocente()" as UC35
}


package "Módulo Sesión" {
  usecase "iniciarSesion()" as UC41
  usecase "cerrarSesion()" as UC42
}
package "Módulo Gestión" {
  usecase "completarGestion()" as UC13

}

admin --> UC13
admin --> UC32
admin --> UC33
admin --> UC34
admin --> UC35
admin --> UC41
admin --> UC42

@enduml