@startuml verAlumnos

skinparam linetype polyline

state ALUMNO_ABIERTO

state verAlumnos as "verAlumnos()" {

    state " " as MostrandoAlumnos
    state " " as FiltrandoAlumnos

    [*] -[#green]-> MostrandoAlumnos 
    note on link
    <b>Docente</b> solicita ver alumnos
    end note    
    
    MostrandoAlumnos -[#green]-> FiltrandoAlumnos
    note on link
    <b>Sistema</b> presenta lista de alumnos
    • DNI, nombre, apellidos
	
    • Permite solicitar filtrar lista
    end note
    
    FiltrandoAlumnos -[#green]-> FiltrandoAlumnos
    note on link
    <b>Docente</b> solicita filtrar lista
    <b>Sistema</b> presenta lista filtrada
    end note
    
}

SISTEMA_DISPONIBLE -[#green]-> verAlumnos

ALUMNO_ABIERTO -[#green]-> verAlumnos

verAlumnos -[#green]-> ALUMNOS_ABIERTO



@enduml     