@startsalt abrirProfesores-wireframe
{ 
<b>Ver Respuestas</b>  
===
{+  CONTENIDO| ¿CORRECTA?| ACCIÓN
  --|--|--
  Reutilizar código de clases existentes | Sí| [Editar] | [Eliminar]
  Capacidad de responder al mismo mensaje | No | [Editar]  | [Eliminar]
  Crear variables globales | Sí | [Editar] | [Eliminar]
  }
  ~~
  .
  {<b>BUSCAR:</b> [                                       ] | [Filtrar]}
  ~~
  .
  {[Crear respuesta] | [Salir]}
}

@endsalt