@startuml 

skinparam linetype polyline

state exportarConfiguracionGlobal as "exportarConfiguracionGlobal"

state exportarGrados as "exportarGrados()" {

    state " " as RequiringExport
    state " " as ProvidingGrados

    [*] -[#green]-> RequiringExport
    note on link
    <b>exportarConfiguracionGlobal</b> solicita exportar Grados
    end note    

    RequiringExport -[#green]-> ProvidingGrados
    note on link
    <b>Sistema</b> permite exportar Grados
    end note

}

exportarConfiguracionGlobal -[#green]-> exportarGrados

@enduml