@startuml cerrarSesion

skinparam linetype polyline

state SISTEMA_DISPONIBLE
state SISTEMA_DISPONIBLE2 as "SISTEMA_DISPONIBLE"

state cerrarSesion as "cerrarSesion()" {

    state " " as SolicitandoCierre
    state " " as ConfirmandoCierre  
    state c <<choice>>

    [*] -[#green]-> SolicitandoCierre 
    note on link
    <b>Administrador institucional o Docente</b> solicita cerrar sesión
    end note    
    
    SolicitandoCierre -[#green]-> ConfirmandoCierre
    note on link
    <b>Sistema</b> permite
    • confirmar cerrar sesión
    • cancelar cerrar sesión
    end note
    
    ConfirmandoCierre -[#green]-> c

}

    SISTEMA_DISPONIBLE -[#green]-> cerrarSesion

    c -[#blue]-> SISTEMA_DISPONIBLE2
    note on link
    <b>Administrador institucional o Docente</b> solicita cancelar cerrar sesión
    end note
    
    c -[#green]-> SESION_CERRADA
    note on link
    <b>Administrador institucional o Docente</b> solicita confirmar cerrar sesión → UsuarioNoRegistrado
    end note


'cerrarSesion -[#green]-> SESION_CERRADA
'note on link
'Administrador → UsuarioNoRegistrado
'iniciarSesion()
'end note

@enduml