@startsalt
{+
  <b>EXPORTAR CONFIGURACIÓN GLOBAL</b>

  {^" Sistema: Error "
    <color:red><b>Error en la exportación</b></color>
    
    .
    ....
    [ Volver a exportar ]
  }
}
@endsalt