@startuml eliminarRespuesta
skinparam linetype polyline

state RESPUESTAS_ABIERTO2 as "RESPUESTAS_ABIERTO"
state RESPUESTAS_ABIERTO3 as "RESPUESTAS_ABIERTO"
state RESPUESTAS_CONTEXTUALES_ABIERTO2 as "RESPUESTAS_CONTEXTUALES_ABIERTO"
state RESPUESTAS_CONTEXTUALES_ABIERTO3 as "RESPUESTAS_CONTEXTUALES_ABIERTO"

state eliminarRespuesta as "eliminarRespuesta()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoRespuesta

    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Docente</b> solicita eliminar respuesta
    end note

    ConfirmandoEliminacion -[#green]-> EliminandoRespuesta
    note on link
    <b>Sistema</b> presenta información de la respuesta a eliminar
    • Contenido
    • Correcta/incorrecta


    • Presenta advertencia de eliminación
    • Permite solicitar confirmar eliminación
    • Permite solicitar cancelar eliminación
    end note

    EliminandoRespuesta -[#green]-> [*]
    note on link
    <b>Docente</b> solicita confirmación de eliminación
    <b>Sistema</b> confirma eliminación
    end note
}

RESPUESTAS_ABIERTO -[#green]-> eliminarRespuesta
RESPUESTAS_CONTEXTUALES_ABIERTO -[#green]-> eliminarRespuesta

eliminarRespuesta -[#green]-> RESPUESTAS_ABIERTO2
note on link
lista actualizada
end note

eliminarRespuesta -[#green]-> RESPUESTAS_CONTEXTUALES_ABIERTO2
note on link
lista actualizada
end note

eliminarRespuesta -[#blue]-> RESPUESTAS_ABIERTO3
note on link
cancelar eliminación
end note

eliminarRespuesta -[#blue]-> RESPUESTAS_CONTEXTUALES_ABIERTO3
note on link
cancelar eliminación
end note

@enduml