@startuml
title Diagrama de Estados - Entidad Examen

 [*] --> Generado : generar
 Generado --> Asignado : asignar
 Asignado --> Resuelto : alumnos realizan el examen
 Resuelto --> Corregido : corregir

@enduml
