@startuml crearPregunta
skinparam linetype polyline


state PREGUNTAS_ABIERTO
state PREGUNTAS_CONTEXTUALES_ABIERTO
state PREGUNTAS_ABIERTO2 as "PREGUNTAS_ABIERTO"
state PREGUNTAS_CONTEXTUALES_ABIERTO2 as "PREGUNTAS_CONTEXTUALES_ABIERTO"
state PREGUNTA_ABIERTO
state PREGUNTA_CONTEXTUAL_ABIERTO


PREGUNTAS_ABIERTO -[#green]-> crearPregunta
PREGUNTAS_CONTEXTUALES_ABIERTO -[#green]-> crearPregunta

state crearPregunta as "crearPregunta()" {

    state " " as SolicitandoDatosPregunta
    state " " as ProcesandoCreacion

    [*] -[#green]-> SolicitandoDatosPregunta 
    note on link
    <b>Docente</b> solicita crear nueva pregunta
    end note    
    
    SolicitandoDatosPregunta -[#green]-> ProcesandoCreacion
    note on link
    <b>Sistema</b> presenta solicitud de datos mínimos:
    ---
    <b>Pregunta:</b>
    • Asignatura (obligatorio)
    • Enunciado (obligatorio)
    • Tema (obligatorio)
    • Dificultad (ENUM: BAJA, MEDIA, ALTA)(obligatorio)

    ---
    • Permite solicitar crear pregunta
    • Permite solicitar cancelar operación
    end note
    
    ProcesandoCreacion -[#green]-> [*]
    note on link
    <b>Docente</b> proporciona datos mínimos
    <b>Sistema</b> crea pregunta y transfiere a edición
    end note
}



crearPregunta -[#green]-> PREGUNTA_ABIERTO
note on link
editarPregunta(nuevaPregunta)
end note

crearPregunta -[#green]-> PREGUNTA_CONTEXTUAL_ABIERTO
note on link
editarPregunta(nuevaPregunta)
end note

crearPregunta -[#blue]-> PREGUNTAS_ABIERTO2
note on link
cancelar creación
end note

crearPregunta -[#blue]-> PREGUNTAS_CONTEXTUALES_ABIERTO2
note on link
cancelar creación
end note

@enduml