@startsalt
{+
  <b>CORREGIR EXÁMENES</b>
  --
  
  <b>Introduzca los exámenes realizados</b>

  [ Cargar exámenes realizados ]
  
  ====
  <color:red><b>¿Confirma corregir exámenes?</b></color>
  ====
  [ Corregir exámenes ] | [ Cancelar ]

}
@endsalt