@startuml importarGrados

skinparam linetype polyline

state GRADOS_ABIERTO2 as "GRADOS_ABIERTO"

state importarGrados as "importarGrados()" {

    state " " as RequiringImport
    state " " as ProvidingGrados
    state " " as ProvidingConfirmation
    state c <<choice>>

    [*] -[#green]-> RequiringImport
    note on link
    <b>Docente</b> solicita importar grados
    end note    

    RequiringImport -[#green]-> ProvidingGrados
    note on link
    <b>Sistema</b> permite 
    • introducir grados a importar
    • salir de importación
    end note

    ProvidingGrados -[#green]-> ProvidingConfirmation
    note on link
    <b>Docente</b> introduce grados a importar
    end note

    ProvidingConfirmation -[#green]-> c
    note on link
    <b>Sistema</b> permite
    • confirmar importación
    • cancelar importación
    end note

    c -[#red]-> ProvidingGrados
    note on link
    Docente cancela importación
    end note

    c -[#red]-> ProvidingGrados
    note on link
    Docente confirma importación: error en la importación
    end note

    c -[#green]-> [*]
    note on link
    Docente confirma importación: importación exitosa
    end note
    
    ProvidingGrados -[#blue]-> [*]
    note on link
    Docente solicita salir de importación
    end note
}

GRADOS_ABIERTO -[#green]-> importarGrados
importarGrados -[#green]-> GRADOS_ABIERTO2

@enduml