@startuml eliminarPregunta
skinparam linetype polyline

' 1. Definición de Estados Externos
state PREGUNTAS_ABIERTO
state PREGUNTAS_ABIERTO2 as "PREGUNTAS_ABIERTO"
state PREGUNTAS_ABIERTO3 as "PREGUNTAS_ABIERTO"
state PREGUNTAS_CONTEXTUALES_ABIERTO
state PREGUNTAS_CONTEXTUALES_ABIERTO2 as "PREGUNTAS_CONTEXTUALES_ABIERTO"
state PREGUNTAS_CONTEXTUALES_ABIERTO3 as "PREGUNTAS_CONTEXTUALES_ABIERTO"

' 2. Transiciones de ENTRADA
PREGUNTAS_ABIERTO -[#green]-> eliminarPregunta
PREGUNTAS_CONTEXTUALES_ABIERTO -[#green]-> eliminarPregunta

state eliminarPregunta as "eliminarPregunta()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoPregunta
     
    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Docente</b> solicita eliminar pregunta
    end note
     
    ConfirmandoEliminacion -[#green]-> EliminandoPregunta
    note on link
    <b>Sistema</b> presenta información de la pregunta:
    • Asignatura 
    • Enunciado 
    • Tema 
    • Dificultad
    • Respuestas 
     
    • Presenta advertencia de eliminación
    • Permite solicitar confirmar eliminación
    • Permite solicitar cancelar eliminación
    end note
     
    EliminandoPregunta -[#green]-> [*]
    note on link
    <b>Docente</b> solicita confirmación de eliminación
    <b>Sistema</b> permite eliminación
    end note

    ' Salida interna de cancelación
    ConfirmandoEliminacion -[#red]-> [*]
}

' 3. Transiciones de SALIDA (Caso: Lista General)

eliminarPregunta -[#green]-> PREGUNTAS_ABIERTO2
note on link
lista actualizada
end note

eliminarPregunta -[#blue]-> PREGUNTAS_ABIERTO3
note on link
cancelar eliminación
end note

' 4. Transiciones de SALIDA (Caso: Lista Contextual)

eliminarPregunta -[#green]-> PREGUNTAS_CONTEXTUALES_ABIERTO2
note on link
lista actualizada
end note

eliminarPregunta -[#blue]-> PREGUNTAS_CONTEXTUALES_ABIERTO3
note on link
cancelar eliminación
end note

@enduml