@startsalt asignarExamenes_FORMULARIO
{
    <b>ASIGNAR EXÁMENES GENERADOS</b>
    ===
    {
        
        <b>Destinatarios:</b>
        ..
        <b>Ingeniería Informática:</b>
        {
            ..
            Búsqueda de alumnos: | "Nombre o DNI    " | [Buscar]
            ..
            [X] Seleccionar todos
            ..
            Alumnos seleccionados manualmente:
            {SI
              [X] Ana Pérez
              [X] Luis Gómez
              [X] María Fernández
              [X] Javier Torres
              [X] Elena Rubio
              [X] Pablo Marín
              [X] Sofía Castro
              [X] Daniel Vico
              [X] Carmen Ruiz
            }
            ..
            Total de alumnos seleccionados: <b>45</b>
        }
        --
        <b>Ingeniería de Organización Industrial:</b>
        {
            ..
            Búsqueda de alumnos: | "Nombre o DNI     " | [Buscar]
            ..
            [X] Seleccionar todos
            ..
            Alumnos seleccionados manualmente:
            {SI
            [X] Marta Soler
            [X] David Ríos
            [X] Laura Vega
            [X] Hugo Sanz
            [X] Paula Nieto
            [X] Rubén Castro
            [X] Andrea Bravo
            [X] Jorge Peña
            [X] Clara Díaz
        }
            ..
            Total de alumnos seleccionados: <b>40</b>
        }
        
        ~~
        .
        <i>El sistema generará una clave alfanumérica al examen de cada alumno.
        
        ~~
        .
        {[Asignar exámenes] | [Salir]}
    }
}
@endsalt