@startuml editarGrado

skinparam linetype polyline

state GRADO_ABIERTO as "GRADO_ABIERTO"
state GRADO_ABIERTO2 as "GRADO_ABIERTO"
state GRADOS_ABIERTO as "GRADOS_ABIERTO"
state GRADOS_ABIERTO2 as "GRADOS_ABIERTO"
state GRADOS_ABIERTO3 as "GRADOS_ABIERTO"

state editarGrado as "editarGrado()" {

    state " " as EditandoDatos
    state " " as GuardandoDatos 

    [*] -[#green]-> EditandoDatos 
    note on link
    <b>Docente</b> solicita editar grado
    end note    
    
    EditandoDatos -[#green]-> GuardandoDatos
    note on link
    <b>Sistema</b> presenta datos de edición
    • Nombre, código
    • Lista de alumnos enlistados
    
    <b>Sistema</b> permite solicitar:
    • modificar campos
    • guardar grado
    • cancelar edición
    • eliminar
    end note
    
    GuardandoDatos -[#green]-> EditandoDatos
    note on link
    <b>Docente</b> solicita modificar campos
    end note
    
    GuardandoDatos -[#green]-> [*]
    note on link
    <b>Docente</b> solicita guardar y salir
    end note

    GuardandoDatos -[#red]-> [*]
    note on link
    <b>Docente</b> solicita cancelar edición
    end note
    
    GuardandoDatos -[#blue]-> [*]
    note on link
    <b>Docente</b> solicita eliminar
    end note

}

GRADO_ABIERTO -[#green]-> editarGrado

GRADOS_ABIERTO -[#green]-> editarGrado

editarGrado -[#green]-> GRADO_ABIERTO2
note on link
guardar
end note

editarGrado -[#red]-> GRADOS_ABIERTO2
note on link
cancelar edición
end note

editarGrado -[#blue]-> GRADOS_ABIERTO3
note on link
eliminar
end note

@enduml