@startuml generar

skinparam linetype polyline

state corregirExamenes as "corregirExamenes()" {

    state " " as RequiringCorrection
    state " " as ProvidingDoneExams
    state " " as ProvidingConfirmation
    state c <<choice>>

    [*] -[#green]-> RequiringCorrection
    note on link
    <b>Docente</b> solicita corregir exámenes
    end note    
    
    RequiringCorrection -[#green]-> ProvidingDoneExams
    note on link
    <b>Sistema</b> permite 
    • introducir exámenes realizados
    • salir de corrección
    end note
    
    ProvidingDoneExams -[#green]-> ProvidingConfirmation
    note on link
    <b>Docente</b> introduce exámenes realizados
    end note
    
    ProvidingConfirmation -[#green]-> c
    note on link
    <b>Sistema</b> permite
    • confirmar corrección
    • cancelar corrección
    end note
    
    c -[#red]-> ProvidingDoneExams
    note on link
    Docente cancela corrección
    end note

    c -[#red]-> ProvidingDoneExams
    note on link
    Docente confirma corrección: error en la corrección
    end note

    c -[#green]-> [*]
    note on link
    Docente confirma corrección: corrección exitosa
    end note
    
    ProvidingDoneExams -[#blue]-> [*]
    note on link
    Docente solicita salir de corrección
    end note
}

SISTEMA_DISPONIBLE -[#green]-> corregirExamenes

corregirExamenes -[#green]-> EXAMENES_CORREGIDOS

@enduml