@startuml verRespuestas

skinparam linetype polyline

state verRespuestas as "verRespuestas()" {

    state " " as MostrandoRespuestas
    state " " as FiltrandoRespuestas

    [*] -[#green]-> MostrandoRespuestas
    note on link
    <b>Docente</b> solicita ver respuestas
    end note    
    
    MostrandoRespuestas -[#green]-> FiltrandoRespuestas
    note on link
    <b>Sistema</b> presenta lista de respuestas
    • Contenido, correcto/incorrecto
    
    • Permite solicitar filtrar lista
    end note
    
    FiltrandoRespuestas -[#green]-> FiltrandoRespuestas
    note on link
    <b>Docente</b> solicita filtrar lista
    <b>Sistema</b> presenta lista filtrada
    end note
}

PREGUNTA_ABIERTO -[#green]-> verRespuestas
RESPUESTA_ABIERTO -[#green]-> verRespuestas
PREGUNTA_CONTEXTUAL_ABIERTO -[#green]-> verRespuestas
RESPUESTA_CONTEXTUAL_ABIERTO -[#green]-> verRespuestas

verRespuestas -[#green]-> RESPUESTAS_ABIERTO

verRespuestas -[#green]-> RESPUESTAS_CONTEXTUALES_ABIERTO

@enduml