@startuml importarAlumnos

skinparam linetype polyline

state ALUMNOS_ABIERTO2 as "ALUMNOS_ABIERTO"

state importarAlumnos as "importarAlumnos()" {

    state " " as RequiringImport
    state " " as ProvidingAlumnos
    state " " as ProvidingConfirmation
    state c <<choice>>

    [*] -[#green]-> RequiringImport
    note on link
    <b>Docente</b> solicita importar alumnos
    end note    

    RequiringImport -[#green]-> ProvidingAlumnos
    note on link
    <b>Sistema</b> permite
    • introducir alumnos a importar
    • salir de importación
    end note

    ProvidingAlumnos -[#green]-> ProvidingConfirmation
    note on link
    <b>Docente</b> introduce alumnos a importar
    end note

    ProvidingConfirmation -[#green]-> c
    note on link
    <b>Sistema</b> permite
    • confirmar importación
    • cancelar importación
    end note

    c -[#red]-> ProvidingAlumnos
    note on link
    Docente cancela importación
    end note

    c -[#red]-> ProvidingAlumnos
    note on link
    Docente confirma importación: error en la importación
    end note

    c -[#green]-> [*]
    note on link
    Docente confirma importación: importación exitosa
    end note
    
    ProvidingAlumnos -[#blue]-> [*]
    note on link
    Docente solicita salir de importación
    end note
}

ALUMNOS_ABIERTO -[#green]-> importarAlumnos
importarAlumnos -[#green]-> ALUMNOS_ABIERTO2

@enduml