@startuml 

skinparam linetype polyline

state exportarConfiguracionGlobal as "exportarConfiguracionGlobal"

state exportarAlumnos as "exportarAlumnos()" {

    state " " as RequiringExport
    state " " as ProvidingAlumnos

    [*] -[#green]-> RequiringExport
    note on link
    <b>exportarConfiguracionGlobal</b> solicita exportar Alumnos
    end note    

    RequiringExport -[#green]-> ProvidingAlumnos
    note on link
    <b>Sistema</b> permite exportar Alumnos
    end note

}

exportarConfiguracionGlobal -[#green]-> exportarAlumnos

@enduml