@startuml completarGestion
skinparam linetype polyline

state completarGestion as "completarGestion()" {

    state " " as PresentandoOpciones

    [*] -[#green]-> PresentandoOpciones 
    note on link
    <b>Administrador institucional o Docente</b> solicita disponibilizar sistema
    end note
    
    PresentandoOpciones -[#green]-> [*]
    note on link
    <b>Sistema</b> permite ser disponibilizado
    end note
}


GRADOS_ABIERTO -[#green]->  completarGestion 

ASIGNATURAS_ABIERTO -[#green]->  completarGestion 

ALUMNOS_ABIERTO -[#green]-> completarGestion  

PREGUNTAS_ABIERTO -[#green]-> completarGestion 

EXAMENES_ASIGNADOS-[#green]-> completarGestion 

EXAMENES_CORREGIDOS -[#green]-> completarGestion 

DOCENTES_ABIERTO -[#green]-> completarGestion 

completarGestion -[#green]-> SISTEMA_DISPONIBLE

@enduml