@startuml eliminarAlumno
skinparam linetype polyline

state ALUMNO_ABIERTO
state ALUMNOS_ABIERTO2 as "ALUMNOS_ABIERTO"
state ALUMNOS_ABIERTO3 as "ALUMNOS_ABIERTO"
state ALUMNOS_ABIERTO4 as "ALUMNOS_ABIERTO"

state eliminarAlumno as "eliminarAlumno()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoAlumno
    
    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Docente</b> solicita eliminar alumno
    end note
    
    ConfirmandoEliminacion -[#green]-> EliminandoAlumno
    note on link
    <b>Sistema</b> presenta información del alumno a eliminar
    • Nombre 
    • Apellidos
    • DNI
    
    • Presenta advertencia de eliminación
    • Permite solicitar confirmar eliminación
    • Permite solicitar cancelar eliminación
    end note
    
    EliminandoAlumno -[#green]-> [*]
    note on link
    <b>Docente</b> solicita confirmación de eliminación
    <b>Sistema</b> confirma eliminación
    end note
}

ALUMNOS_ABIERTO -[#green]-> eliminarAlumno
ALUMNO_ABIERTO -[#green]-> eliminarAlumno

eliminarAlumno -[#green]-> ALUMNOS_ABIERTO2
note on link
lista actualizada
end note

eliminarAlumno -[#blue]-> ALUMNOS_ABIERTO3
note on link
cancelar eliminación
end note

eliminarAlumno -[#blue]-> ALUMNOS_ABIERTO4
note on link
cancelar eliminación
end note

@enduml