@startuml
skinparam linetype polyline

state DOCENTES_ABIERTO as "DOCENTES_ABIERTO"
state DOCENTES_ABIERTO2 as "DOCENTES_ABIERTO"
state DOCENTE_ABIERTO as "DOCENTE_ABIERTO"
state DOCENTE_ABIERTO2 as "DOCENTE_ABIERTO"
state DOCENTES_ABIERTO3 as "DOCENTES_ABIERTO"

DOCENTES_ABIERTO -[#green]-> editarDocente

DOCENTE_ABIERTO -[#green]-> editarDocente

state editarDocente as "editarDocente()" {

    state " " as EditandoDatos
    state " " as GuardandoDatos 

    [*] -[#green]-> EditandoDatos 
    note on link
    <b>Administrador institucional</b> solicita editar docente
    end note    
    
    EditandoDatos -[#green]-> GuardandoDatos
    note on link
    <b>Sistema</b> presenta datos de edición
    • Nombre 
    • Apellidos 
    • DNI 
    • Nombre de usuario 
    • Email 
    • Password
    
    <b>Sistema</b> permite solicitar:
    • modificar campos
    • guardar docente
    • cancelar edición
    • eliminar
    end note
    
    GuardandoDatos -[#green]-> EditandoDatos
    note on link
    <b>Administrador institucional</b> solicita modificar campos
    end note
    
    GuardandoDatos -[#green]-> [*]
    note on link
    <b>Administrador institucional</b> solicita guardar y salir
    end note
    
    GuardandoDatos -[#blue]-> [*]
    note on link
    <b>Administrador institucional</b> solicita eliminar
    end note

    GuardandoDatos -[#red]-> [*]
    note on link
    <b>Administrador institucional</b> solicita cancelar edición
    end note
}

editarDocente -[#green]-> DOCENTE_ABIERTO2
note on link
guardar
end note

editarDocente -[#red]-> DOCENTES_ABIERTO2
note on link
cancelar edición
end note

editarDocente -[#blue]-> DOCENTES_ABIERTO3
note on link
eliminar
end note

@enduml