@startuml crearDocente

skinparam linetype polyline

state DOCENTES_ABIERTO
state DOCENTES_ABIERTO2 as "DOCENTES_ABIERTO"

DOCENTES_ABIERTO -[#green]-> crearDocente

state crearDocente as "crearDocente()" {

    state " " as SolicitandoDatos
    state " " as CreandoDocente

    [*] -[#green]-> SolicitandoDatos 
    note on link
    <b>Administrador institucional</b> solicita crear docente nuevo
    end note    
    
    SolicitandoDatos -[#green]-> CreandoDocente
    note on link
    <b>Sistema</b> presenta solicitud de datos mínimos del docente
    • Nombre (obligatorio)
    • Apellidos (obligatorio)
    • DNI (obligatorio)
    • Nombre de usuario (obligatorio)
    • Email (obligatorio)
    • Password (obligatorio)
    
    • Permite solicitar crear docente
    • Permite solicitar cancelar creación
    end note
    
    CreandoDocente -[#green]-> [*]
    note on link
    <b>Administrador institucional</b> proporciona datos mínimos
    <b>Sistema</b> crea docente y transfiere a edición
    end note
}

crearDocente -[#green]-> DOCENTE_ABIERTO
note on link
editarDocente(docenteNuevo)
end note

crearDocente -[#blue]-> DOCENTES_ABIERTO2
note on link
cancelar creación
end note

@enduml